swagger: '2.0'
info:
  version: v1.0
  title: Subscription API
  description: >
    An Subscription represents a listing of goods and services a customer has been charged
    for over a specific time period. It is intended as a reporting and communication
    tool for recurring payments.
host: api.hanzo.ai
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.ai/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

paths:
  '/subscription/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: deleteSubscription
      description: >
        Completely deletes the associated Subscription.  Cannot be undone.
      produces:
        - text/html
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '204':
          description: 'Everything is OK.'
          schema:
            type: object
            properties: {}
          examples:
            application/json: null

    get:
      operationId: getSubscription
      description: >
        Returns a specified subscription.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Subscription'

    patch:
      operationId: updateSubscription
      description: >
        Updates the specified Subscription object piecemeal. Any fields not
        included are not updated.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Subscription'
      responses:
        '200':
          description: 'Everything is OK.'
          schema:
            $ref: '#/definitions/Subscription'

    put:
      operationId: replaceSubscription
      description: >
        Wholly replaces the specified Subscription object in-place. Any fields not
        included will be blanked.
      responses:
        '200':
          description: 'Everything is OK.'
          schema:
            $ref: '#/definitions/Subscription'

  /subscription:
    post:
      operationId: createSubscription
      description: >
        Creates a new Subscription.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Subscription'
      responses:
        '201':
          description: 'Everything is OK. New subscription created.'
          schema:
            $ref: '#/definitions/Subscription'

    get:
      operationId: retrieveSubscription
      description: Returns a list of all available subscriptions.
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SubscriptionArray'

definitions:
  Subscription:
    title: Subscription
    type: object
    properties:
      createdAt:
        type: string
        description: The time this object was created. Conforms to RFCE3339.
      updatedAt:
        type: string
        description: The time this object was last updated. Conforms to RFCE3339.
      id:
        type: string
        description: The hanzo-assigned guid to identify this item.
      account:
        type: object
      currency:
        type: string
        description: >
          The three-digit identifier for the currency the subscription
          was made in. USD = United States Dollar, JPY = Japanese Yen, etc.
      billing:
        type: string
        description: >
          Either 'chargeImmediately' or 'sendInvoice', this denotes how
          billing is handled on the subscription.
      billingScheme:
        type: string
        description: Describes how to interpret the price per period.
      interval:
        type: string
        description: The unit used in determining the lapse between billing cycles.
      intervalCount:
        type: integer
        description: >
          The number of units making up a billing cycle - e.g., 30, combining
          with the interval of 'days' to make 30 days.
      amountDue:
        type: integer
        format: int64
        description: >
          The specific quantity of money due. Represented in the least significant
          unit in the associated currency (so cent for USD, which has partial Dollars, but Yen
          for JPY, which has no concept of partial Yen.)
      amountPaid:
        type: integer
        format: int64
        description: >
          The specific quantity of money paid. Represented in the least significant
          unit in the associated currency (so cent for USD, which has partial Dollars, but Yen
          for JPY, which has no concept of partial Yen.)
      amountRemaining:
        type: integer
        format: int64
        description: >
          The specific quantity of money ultimately scheduled to be paid. Represented in the least significant
          unit in the associated currency (so cent for USD, which has partial Dollars, but Yen
          for JPY, which has no concept of partial Yen.)
      cancelAtPeriodEnd:
        type: boolean
        description: Whether nor the subscription will terminate at the end of its current billing cycle.
      daysUntilDue:
        type: integer
        description: How many days before the subscription is due to be billed.

  SubscriptionArray:
    title: SubscriptionArray
    description: An array of Subscriptions
    type: array
    items:
      $ref: '#/definitions/Subscription'
