swagger: '2.0'
info:
  version: v1.0
  title: Checkout API
  description: >
    The Checkout API enables you to quickly create a new order and capture payment in a single call.
host: api.hanzo.io
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.io/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

paths:
  '/checkout/capture/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    post:
      operationId: capturePayment
      description: >
        Captures a specified order. Second step in the two-step payment process.
      parameters:
        - name: token
          in: query
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              orderId:
                type: string
            example:
              orderId: 3NiN5emSwHRrAvlTlZgO
        - name: Accept
          in: header
          type: string
        - name: Content-Type
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Order'

  /checkout/charge:
    post:
      operationId: chargePayment
      description: >
        Authorizes and charges an included order in a one-step process.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
        - name: Content-Type
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Order'

  /checkout/authorize:
    post:
      operationId: authorizePayment
      description: >
        Captures a specified order. First step in the two-step payment process.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Content-Type
          in: header
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Order'
