swagger: '2.0'
info:
  version: v1.0
  title: Product API
  description: >
    A product represents a specific offering in your store. Typically,
    these are unique and distinct things or services; for closely related things
    or services, consider using the Variant API.
host: api.hanzo.ai
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.ai/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

paths:
  /product:
    post:
      operationId: createProduct
      description: Creates a new product
      parameters:
        - name: token
          in: query
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Product'

    get:
      operationId: getProduct
      description: >
        Gets a list of all available products.
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ProductArray'

  '/product/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string

    patch:
      operationId: updateProduct
      description: >
        Replaces a product piecemeal. Parameters not passed are not updated.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Product'

    get:
      operationId: retrieveProduct
      description: >
        Retrieves a specified product
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Product'

    delete:
      operationId: deleteProduct
      description: >
        Permanently deletes a specified product. Cannot be undone.
      produces:
        - text/html
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '204':
          description: ''
          schema:
            type: object
            properties: {}
          examples:
            application/json: null

    put:
      operationId: replaceProduct
      description: >
        Wholly replaces a given product. Parameters not passed are blanked.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Product'

definitions:
  Product:
    title: Product
    type: object
    properties:
      id:
        type: string
        description: The hanzo-assigned guid to identify this item.
      createdAt:
        type: string
        description: The time this Product was created. Conforms to RFC3339.
      updatedAt:
        type: string
        description: The time this Product was last updated. Conforms to RFC3339.
      slug:
        type: string
        description: The human-readable URL extension for this product.
      title:
        type: string
        description: The human-friendly banner for this product.
      headline:
        type: string
        description: The tag line for this product.
      excerpt:
        type: string
        description: A high visiblity selection.
      description:
        type: string
        description: The long form depiction.
      released:
        type: string
        description: The date this product was released. Conforms to RFC3339.
      available:
        type: boolean
        description: Whether or not the product is able to be purchased.

  ProductArray:
    title: ProductArray
    description: An array of Products
    type: array
    items:
      $ref: '#/definitions/Product'
