swagger: '2.0'
info:
  version: v1.0
  title: Affiliate API
  description: >
    An Affiliate is an influencer who is generating sales for a commission.
host: api.hanzo.io
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.io/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

paths:
  '/affiliate/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    patch:
      operationId: updateAffiliate
      description: >
        Replaces a affiliate piecemeal. Any fields not included are not affected.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Affiliate'
      responses:
        '200':
          description: 'Everything is OK.'
          schema:
            $ref: '#/definitions/Affiliate'
    delete:
      operationId: deleteAffiliate
      description: >
        Permanently deletes the requested Affiliate. Cannot be undone.
      responses:
        '204':
          description: 'Everything is OK.'
          schema:
            type: object
            properties: {}

    get:
      operationId: retrieveAffiliate
      description: >
        Gets the requested affiliate.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Affiliate'

    put:
      operationId: replaceAffiliate
      description: >
        Replaces a affiliate wholly. Any fields not included are blanked.
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Affiliate'

  '/affiliate/{id}/connect':
    parameters:
      - name: id
        in: path
        required: true
        type: string

    get:
      operationId: connectAffiliate
      description: >
        Redirects the affiliate to Stripe to connect their account.
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '302':
          description: 'Refers over to stripe for connection.'
          schema:
            $ref: '#/definitions/ReferralArray'

  /affiliate:
    get:
      operationId: retrieveAllAffiliates
      description: >
        Gets a list of all available affiliates.
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/AffiliateArray'

    post:
      operationId: createAffiliate
      description: >
        Creates a new affiliate.
      parameters:
        - name: token
          in: query
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Affiliate'
      responses:
        '201':
          description: 'Everything is OK. New Affiliate created.'
          schema:
            $ref: '#/definitions/Affiliate'

  '/affiliate/{id}/transactions':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: getAffiliateTransactions
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  description: The hanzo-assigned guid to identify this item.
                createdAt:
                  type: string
                  description: The time this Transaction was created. Conforms to RFC3339.
                updatedAt:
                  type: string
                  description: The time this Transaction was last updated. Conforms to RFC3339.
                userId:
                  type: string
                  description: The ID for the user that initiated this transaction.
                type:
                  type: string
                  description: The general type of transaction.
                currency:
                  type: string
                  description: >
                    The type of money used on the transaction. USD for United States
                    Dollar, JPY for Japanese yen, etc. Conforms to ISO 4217 codes.
                amount:
                  type: integer
                  description: >
                    The quantity of money involved in the Transaction. Represented in
                    the least significant denomination possible in the given currency - so
                    cents in USD, yen in JPY, etc.
                test:
                  type: boolean
                  description: Whether or not this transaction is a test.
                notes:
                  type: string
                  description: Supplementary text regarding the transaction.
                tags:
                  type: string
                  description: A collection of meta-identifiers for the transaction.
                sourceId:
                  type: string
                sourceKind:
                  type: string
          examples:
            application/json:
              - id: 0gizw8Z2hEdk2
                createdAt: '2016-04-15T04:54:44.119563Z'
                updatedAt: '2016-04-15T04:54:44.119563Z'
                userId: w4HZNvlwsQ2nO
                type: deposit
                currency: points
                amount: 1
                test: false
                notes: Deposit from referral JJFx6Gku71rj
                tags: referral
                sourceId: JJFx6Gku71rj
                sourceKind: affiliate

  /referral:
    get:
      operationId: returnAllReferrals
      description: >
        Returns all available referrals.
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ReferralArray'

    post:
      operationId: createReferral
      description: >
        Creates a new referral.
      parameters:
        - name: token
          in: query
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Referral'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Referral'
  '/referral/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: deleteReferral
      description: >
        Deletes the requested Referral.  Cannot be undone.
      responses:
        '204':
          description: ''

    get:
      operationId: retrieveReferral
      description: >
        Gets the requested referral.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Affiliate'

    patch:
      operationId: updateReferral
      description: >
        Replaces the Referral piecemeal. Any fields not included are ignored.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: body
          in: body
          schema:
            properties:
              id:
                type: string
            type: object
            example:
              id: OxslNprfZvDW
        - name: Accept
          in: header
          required: false
          type: string
        - name: Content-Type
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Affiliate'

    put:
      operationId: replaceReferral
      description: >
        Replaces the Referral wholly. Any fields not included will be blanked.
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Affiliate'

definitions:
  Affiliate:
    title: Affiliate
    type: object
    properties:
      id:
        type: string
        description: The hanzo-assigned guid to identify this item.
      createdAt:
        type: string
        description: The time this Affiliate was created. Conforms to RFC3339.
      updatedAt:
        type: string
        description: The time this Affiliate was last updated. Conforms to RFC3339.
      userId:
        type: string
        description: The ID denoting the user account of this affiliate.
      name:
        type: string
        description: The friendly name of this affiliate.
      company:
        type: string
        description: The company this affiliate is associated with.
      taxId:
        type: string
        description: The affiliate's tax id.
      timeZone:
        type: string
        description: The affiliate's time zone.
      couponId:
        type: string
        description: The ID of the coupon that the affiliate uses to drive sales.
      schedule:
        $ref: '#/definitions/Schedule'
      commission:
        $ref: '#/definitions/Commission'

  Commission:
    title: Commission
    description: A commission schedule
    type: object
    properties:
      minimum:
        type: integer
        description: >
          The minimum amount of currency to be awarded per sale, expressed in the
          settlement currency's smallest unit (usually USD, which implies cents).
      percent:
        type: number
        description: >
          A percentage of each gross (before taxes, shipping, etc) sale that is
          credited to the Affiliate.
      flat:
        type: integer
        description: >
          The flat amount of currency credited per sale, expressed in the settlement
          currency's smallest unit (usually USD, which implies cents).

  Schedule:
    title: Schedule
    description: A pay schedule
    type: object
    properties:
      type:
        type: string
        description: >
          A general indicator for the payment schedule. One of 'daily-rolling',
          'weekly-anchored', 'monthly-anchored'.
      period:
        type: integer
        description: Associated with 'daily-rolling', this is the number of days between payment.
      weeklyAnchor:
        type: string
        description: Associated with 'weekly-anchored', this is the day of the week when the payment goes out.
      monthlyAnchor:
        type: integer
        description: Associated with 'monthly-anchored', this is the day of the month when payment goes out.


  AffiliateArray:
    title: AffiliateArray
    description: An array of Affiliates
    type: array
    items:
      $ref: '#/definitions/Affiliate'

