swagger: '2.0'
info:
  version: v1.0
  title: Chain API
  description: >
    A Chain represents a base price, cycle, and currency for a subscription.

host: api.hanzo.ai
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.ai/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

paths:
  '/chain/{chainName}/{blockNumber}':
    parameters:
      - name: chainName
        in: path
        required: true
        type: string
      - name: blockNumber
        in: path
        required: true
        type: string

    get:
      operationId: getChainBlock
      description: >
        Returns a requested block in a specific chain.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Block'

  '/chainaddress/{chainName}/{address}':
    parameters:
      - name: chainName
        in: path
        required: true
        type: string
      - name: address
        in: path
        required: true
        type: string

    get:
      operationId: getChainAddress
      description: >
        Returns information about a specific address
        on the requested block chain.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/BlockAddress'

  '/chaintransaction/{chainName}/{transaction}':
    parameters:
      - name: chainName
        in: path
        required: true
        type: string
      - name: transaction
        in: path
        required: true
        type: string

    get:
      operationId: getChainTransaction
      description: >
        Returns information about a specific transaction
        on the requested block chain.
      parameters:
        - name: token
          in: query
          required: false
          type: string
        - name: Accept
          in: header
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/BlockAddress'

definitions:
  Block:
    title: Block
    type: object
    properties:
      createdAt:
        type: string
        description: The time this object was created. Conforms to RFCE3339.
      updatedAt:
        type: string
        description: The time this object was last updated. Conforms to RFCE3339.
      id:
        type: string
        description: The hanzo-assigned guid to identify this item.
      blockNumber:
        type: integer
        format: int64
        description: >
          The block number from the parent chain.
      blockHash:
        type: string
        description: The stringified hash of the entire block.
      blockTime:
        type: integer
        format: int64
        description: The timestamp when the block took to publish.
      blockMedianTime:
        type: integer
        format: int64
        description: The median time blocks are taking to publish on the whole chain at this point.
      blockNonce:
        type: integer
        format: int64
        description: The nonce used in the block.
      blockDifficulty:
        type: integer
        format: int64
        description: The block's issued difficulty.

  BlockAddress:
    title: BlockAddress
    type: object
    properties:
      createdAt:
        type: string
        description: The time this object was created. Conforms to RFCE3339.
      updatedAt:
        type: string
        description: The time this object was last updated. Conforms to RFCE3339.
      walletId:
        type: string
        description: The hanzo-assigned guid to identify this item.
      address:
        type: string
        description: The address used by the wallet on its parent blockchain.
      type:
        type: string
        description: The name of the host blockchain ('bitcoin', 'ethereum', etc).

  BlockTransaction:
    title: BlockTransaction
    type: object
    properties:
      createdAt:
        type: string
        description: The time this object was created. Conforms to RFCE3339.
      updatedAt:
        type: string
        description: The time this object was last updated. Conforms to RFCE3339.
      Id:
        type: string
        description: The hanzo-assigned guid to identify this item.
      transactionId:
        type: string
        description: >
          The identifier for this transaction on the block chain. The context of this
          varies quite a lot - Bitcoin, for example, has unique IDs for each transaction,
          while Ethereum uses the block number and its offset index. This will always
          contain whatever data is used in the blockchain itself to uniquely identify
          transactions.
      from:
        type: string
        description: >
          The originator(s) of the transaction. In cases where there are multiple
          senders, this will list them all, comma separated.
      to:
        type: string
        description: >
          The receiver(s) of the transaction. In cases where there are multiple
          receivers, this will list them all, comma separated.
      time:
        type: string
        description: A timestamp of when this transaction was accepted into the blockchain.
