
swagger: '2.0'
info:
  version: v1.0
  title: Account API
  description: >
    An Account represents a user's records on your store
    or in your website. They are used to provide a
    persistent identity for the user, and also to help
    tie disparate records together (such as
    shipping/billing addresses, and historical orders).
host: api.hanzo.ai
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.ai/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query

paths:
  /account/login:
      post:
        operationId: accountLogin
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: token
            in: query
            type: string
          - name: '{"email":"test@email.com","password":"0k9q91"}'
            in: formData
            type: string
          - name: Content-Type
            in: header
            type: string
          - name: Accept
            in: header
            type: string
        responses:
          '200':
            description: 'Successful login.'
            schema:
              type: object
              properties:
                token:
                  type: string
            examples:
              application/json:
                token: >
                  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0NjA2OTYwOTgsImV4cCI6MTQ2MDc4MjQ5OCwiaXNzIjoieTVJWjNHYkZsalJRIiwianRpIjoidWtxUDJSU2FWNW8iLCJGaXJzdE5hbWUiOiIiLCJMYXN0TmFtZSI6IiIsImFwcCI6IlN0b3JlIiwidXNyIjoiUnlIMDI2QnUyM0cxIiwib3JnIjoic3VjaHRlZXMiLCJ0eXAiOiJjdXN0b21lciIsInRzdCI6dHJ1ZSwiYml0Ijo0NTAzNjE3MDc1Njc1MTc2fQ.dQZt_A9rLBpmBYu-QpaRdU4XlwwG5SyMv25rVqrz7a0
          '401':
            description: ''
            schema:
              type: object
              properties:
                error:
                  type: object
                  properties:
                    type:
                      type: string
                    message:
                      type: string
            examples:
              application/json:
                error:
                  type: api-error
                  message: Email or password is incorrect

  /account:
    patch:
      operationId: updateAccount
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/Account'
      responses:
        '200':
          description: 'Everything is OK!'
          schema:
            $ref: '#/definitions/Account'

    get:
      operationId: returnAccount
      parameters:
        - name: token
          in: query
          type: string
        - name: Accept
          in: header
          type: string
      responses:
        '200':
          description: 'Everything is OK!'
          schema:
            $ref: '#/definitions/Account'

  /account/create:
    post:
      operationId: createAccount
      parameters:
        - name: token
          in: query
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Account'
      responses:
        '201':
          description: 'Everything is OK - Account created.'
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: 'Bad request - see error message'
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  type:
                    type: string
                  message:
                    type: string
          examples:
            application/json:
              error:
                type: api-error
                message: Email is not valid

definitions:
  Account:
    title: Account
    description: >
      An Account model, usable in POST, PUT, or PATCH requests,
      and returned as a response from GET, POST, PUT, and PATCH.
    type: object
    properties:
      id:
        type: string
        description: The hanzo-assigned guid to identify this item.
      createdAt:
        type: string
        description: The time this Variant was created. Conforms to RFC3339.
      updatedAt:
        type: string
        description: The time this Variant was last updated. Conforms to RFC3339.
      userName:
        type: string
        description: The user's elected name for the site/store.
      firstName:
        type: string
        description: The user's first (given) name.
      lastName:
        type: string
        description: The user's last name (surname).
      company:
        type: string
        description: The name of the company the account represents.
      phone:
        type: string
        description: The contact phone number for the account.
      billingAddress:
        type: object
        description: The physical location used to charge orders.
      shippingAddress:
        type: object
        description: The physical location orders are sent to.
      email:
        type: string
        description: The contact email, used for updates and other communication.
